[package]
name = "thesis"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.15.9"
csv = "1.3.1"
plotters = "0.3.7"
rand = "0.9.0"
rand_chacha = "0.9.0"
serde = "1.0.219"
walkdir = "2.5.0"
