description = "Figure 2b ff=1.0"

[simulation]
seeds = 1
max_time_step = 100000
population = 20
dynamic_rank = false
output_directory = "ff_1.0"

[agent_parameters]
strat_learning_speed = 0.01
net_learning_speed = 0.0
strat_discount = 0.01
net_discount = 0.0
strat_tremble = 0.01
net_tremble = 0.01

[payoffs]
hd = 1.0
dh = 0.4
dd = 0.6
hh_f = 1.0

[csv]
weights = false
scores = false
totalinteractions = false
evostats = false
strategyvisit = true
strategyhost = true
netstd = false
outscore = true
totalpayoff = false
