description = "Figure 2b ff=0.6"

[simulation]
seeds = 1
max_time_step = 100000
population = 50
dynamic_rank = false
output_directory = "ff_0.6"

[agent_parameters]
strat_learning_speed = 0.01
net_learning_speed = 0.01
strat_discount = 0.01
net_discount = 0.01
strat_tremble = 0.01
net_tremble = 0.01

[payoffs]
hd = 1.0
dh = 0.4
dd = 0.6
hh_f = 0.6
