run:
	python3 -O generate_foxweight.py
	python3 -O generate_morality.py
	python3 -O generate_strategy.py
	python3 -O generate_cumulativepayoffs.py
	python3 -O generate_cycles.py
	python3 -O generate_foxweighttable.py
	python3 -O generate_totalpayoffs.py
	python3 -O generate_purehawks.py
	python3 -O generate_foxuse.py
